# Generated by Django 5.0.7 on 2024-07-17 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Men'), ('F', 'Female'), ('U', 'Unisex'), ('N', 'Null')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=50)),
                ('inventory', models.IntegerField()),
                ('sku', models.CharField(max_length=20)),
                ('cost', models.FloatField()),
                ('description', models.TextField()),
                ('upc', models.IntegerField()),
                ('weight', models.FloatField()),
                ('image_url', models.URLField()),
                ('msrp', models.FloatField()),
                ('additional_upc', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brands')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('sex', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.genre')),
                ('product_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.producttype')),
            ],
        ),
    ]
